### ISSUE TITLE
Recording files names

### ISSUE THREAD

**Issue by Aculisme** [beatleuk/gdfl#1]
Hey @beatleuk, 

Is there any change that file names could be added as a feature (possibly toggleable, using the -f (for files) flag)? I'm using this script for creating a directory of my organization's google drive folder, but it would definitely benefit from displaying not only folder names, but those of the files within the folders as well.

E.g.

$python3 gdfl.py -f 1WEMncIM0FevDzrVwDDmfLhd4-kfO0GH 

Would result in:

>Main folder
--> subfolder 1
----> file 1
----> file 2
--> subfolder 2
--> file 3

**Comment by beatleuk** [comment]
Hey @Aculisme,

It would be easy enough to create another function for reading of child files in each folder if the switch was passed in the command line and I'll take a look at it in a bit but can't promise when it would be done by.

BeatleUK

**Comment by beatleuk** [comment]
Hi @Aculisme, I have added the -c arg to include all files in the folders as requested:
e.g. _python gdfl.py -f FOLDER_ID -c_

**Comment by Aculisme** [comment]
You're a saint! Thanks!
