### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by bbarrows89** [beatleuk/gdfl#3]
`(venv)  ✘  ~/Desktop/googledrive  python3 goog.py -f 1hz0MlGExRjr-JIrzqG1wnUs6fK4nm0Lc
Folder ID 1hz0MlGExRjr-JIrzqG1wnUs6fK4nm0Lc is a Google Drive Folder called: Test Folder
Traceback (most recent call last):
  File "goog.py", line 309, in <module>
    main()
  File "goog.py", line 247, in main
    childname = unicode(foldername, "utf-8")
NameError: name 'unicode' is not defined`

**Comment by beatleuk** [comment]
Hi @bbarrows89, sorry I didn't see this until now but I believe this is because you are running python 3 which doesn't cater for unicode, I'll have to work on making it python 3 compatible.

**Comment by beatleuk** [comment]
Script has been updated for Python 3 and still works on python 2
