### ISSUE TITLE
ImportError: cannot import name errors

### ISSUE THREAD

**Issue by HonzaKopecky** [beatleuk/gdfl#5]
I tried to run this script using both python v2 ans python v3. Neither of them managed to run the script. I installed the required packages using pip and when I run the script I get the following error:

```
Traceback (most recent call last):
  File "gdfl.py", line 9, in <module>
    from apiclient import errors, discovery
ImportError: cannot import name 'errors'
```

Am I doing something wrong?

**Comment by beatleuk** [comment]
Hi,

Import errors comes from line 9 in the code: `apiclient import errors, discovery`
This relies on you having the Google Drive API python client installed as per https://developers.google.com/drive/api/v3/quickstart/python:
`pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib`
Then that should fix it for Python V2

**Comment by HonzaKopecky** [comment]
Hello,

well, shouldn't this be documented somewhere? I expected that I need to install some packages but when I used just the names from python script I got completely different packages then the ones I needed.

Thanks, it runs now.
